name: Build and Deploy

on:
  push:
    branches:
      - feature/dev

env:
  RESOURCE_GROUP: rg-csp-web-demo-scus
  WEBAPP_NAME: asp-csp-web-demo-scus
  SLOT_NAME: staging

jobs:
  backend-deploy:
    name: Build & Deploy Backend (.NET API)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI login with individual parameters
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_CLIENT_ID }}" \
            -p "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # ⭐ FIXED: Publish ONLY correct csproj
      - name: Publish Backend API
        run: |
          dotnet publish src/csp.api/csp.api.csproj -c Release -o backend-publish

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: ./backend-publish


  frontend-deploy:
    name: Build & Deploy Frontend (.NET UI)
    runs-on: ubuntu-latest
    needs: backend-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI login with individual parameters
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_CLIENT_ID }}" \
            -p "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # ⭐ FIXED: Publish correct frontend UI project
      - name: Publish Frontend UI
        run: |
          dotnet publish frontend/CloudSolutionProvider/CloudSolutionProvider-UI/*.csproj -c Release -o frontend-publish

      - name: Deploy Frontend to Slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          package: ./frontend-publish
