name: CSP App Deploy - DEV

on:
  workflow_run:
    workflows: ["CSP Infra Deploy - DEV"]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev
  WEBAPP_NAME: app-csp-web-dev-scus
  RESOURCE_GROUP: rg-csp-web-dev-scus

jobs:
  build-and-deploy:
    name: Build & Deploy App (DEV)
    runs-on: ubuntu-latest

    # âœ… Only run if infra workflow succeeded OR manual trigger
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/web

      - name: Build
        run: dotnet build src/web --configuration Release

      - name: Test
        run: dotnet test src/web

      - name: Publish
        run: |
          dotnet publish src/web \
            -c Release \
            -o publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy to Staging Slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: staging
          package: publish

      - name: Swap Slots
        run: |
          az webapp deployment slot swap \
            --resource-group $RESOURCE_GROUP \
            --name $WEBAPP_NAME \
            --slot staging

      - name: Deployment Summary
        run: |
          echo "## ðŸŒ Application Deployment Completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Web App: $WEBAPP_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: DEV" >> $GITHUB_STEP_SUMMARY
