name: CSP Infra Deploy - DEV

on:
  push:
    branches: [develop]
    paths:
      - infra/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev
  LOCATION: southcentralus
  PROJECT_NAME: csp

jobs:
  validate:
    name: Validate Bicep Templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Bicep Build
        run: |
          echo "ðŸ” Validating Bicep syntax"
          az bicep build --file infra/main.bicep

      - name: What-If Deployment
        run: |
          echo "ðŸ” Running what-if"
          az deployment sub what-if \
            --location $LOCATION \
            --template-file infra/main.bicep \
            --parameters infra/parameters/dev.bicepparam

  deploy:
    name: Deploy Infrastructure (DEV)
    needs: validate
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy Infra via Bicep
        run: |
          echo "ðŸš€ Deploying infrastructure via Bicep"
          az deployment sub create \
            --location $LOCATION \
            --template-file infra/main.bicep \
            --parameters infra/parameters/dev.bicepparam \
            --name csp-infra-dev-${{ github.run_id }}

      - name: Deployment Summary
        run: |
          echo "## ðŸ—ï¸ Infrastructure Deployment Completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: DEV" >> $GITHUB_STEP_SUMMARY
          echo "- Location: $LOCATION" >> $GITHUB_STEP_SUMMARY
          echo "- Deployment Name: csp-infra-dev-${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
