name: Deploy API & UI - DEMO

on:
  push:
    branches:
      - feature/dev

permissions:
  id-token: write
  contents: read

env:
  API_WEBAPP: app-csp-api-demo-scus
  UI_WEBAPP: app-csp-ui-demo-scus

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # -------- API ----------
      - name: Publish API
        run: |
          dotnet publish src/csp.api/csp.api.csproj -c Release -o api-publish
          ls -la api-publish

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.API_WEBAPP }}
          package: api-publish

      # -------- UI ----------
      - name: Publish UI
        run: |
          dotnet publish frontend/CloudSolutionProvider/CloudSolutionProvider-UI/CloudSolutionProvider-UI.csproj -c Release -o ui-publish
          ls -la ui-publish

      - name: Deploy UI
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.UI_WEBAPP }}
          package: ui-publish
